---

- name: Install zip/unzip/gzip/nano CentOS
  become: yes
  become_method: sudo
  yum:
   name:
    - zip
    - unzip
    - gzip
    - nano
   state: latest
  when: ansible_os_family == "RedHat"
  tags: install_centos

- name: Install zip/unzip/gzip/nano Debian/Ubuntu
  become: yes
  become_method: sudo
  apt:
   name:
    - zip
    - unzip
    - gzip
    - nano
   state: latest
  when: ansible_os_family == "Debian"
  tags: install_debian

- name: Install zip/unzip/gzip/nano FreeBSD
  become: yes
  become_method: su
  pkgng:
   name:
    - zip
    - unzip
    - gzip
    - nano
   state: latest
  when: ansible_os_family == "FreeBSD"
  tags: install_freebsd


- name: Uninstall zip/nano CentOS
  become: yes
  become_method: sudo
  yum:
   name:
    - unzip
    - nano
   state: removed
  when: ansible_os_family == "RedHat"
  tags: uninstall_centos

- name: Uninstall zip/nano Debian/Ubuntu
  become: yes
  become_method: sudo
  apt:
   name:
    - unzip
    - nano
   state: removed
  when: ansible_os_family == "Debian"
  tags: uninstall_debian

- name: Uninstall zip/nano FreeBSD
  become: yes
  become_method: su
  pkgng:
   name:
    - unzip
    - nano
   state: absent
  when: ansible_os_family == "FreeBSD"
  tags: uninstall_freebsd

