---
- name: Install epel
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"

- name: Install nginx CentOS
  become: yes
  become_method: sudo
  yum: name=nginx state=present
  when: ansible_os_family == "RedHat"

- name: Install nginx Debian/Ubuntu
  become: yes
  become_method: sudo
  apt: name=nginx state=present
  when: ansible_os_family == "Debian"

- name: Install nginx FreeBSD
  become: yes
  become_method: su
  pkgng: name=nginx state=present
  when: ansible_os_family == "FreeBSD"

  notify: restart nginx
