---
- name: Install zip, unzip, gzip, nano on different VM's
  hosts: all
  roles:
    - zipnano_tags

- hosts: ydBSD
  become:
    true
  become_method:
    su
  become_user:
    root
  remote_user:
    yd
  roles:
   - zipnano_tags


- hosts: centos7
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    yd
  roles:
   - zipnano_tags

- hosts: yd-ubuntu
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    yd
  roles:
   - zipnano_tags